- name: install jenkins
  ansible.builtin.dnf:
    name: 
      - java-17-openjdk
      - fontconfig
    state: present

- name: add jenkins user
  ansible.builtin.user:
    name: jenkins
    password: $6$rounds=100000$qJvM6D3rVG/6Kau5$DBXhDu6cpN.h9USh7/15SdzbL9WDNtinWRoriar4TGiVkOn.7OpzRubNRkxiziwI2G7zzmnIIzlE5dahYKP6x.

- name: create jenkins folder
  ansible.builtin.file:
    path: /jenkins
    owner: jenkins
    group: jenkins
    state: directory