- name: copy jenkins repo file
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install java
  ansible.builtin.dnf:
    name:
      - java-17-openjdk
      - fontconfig

- name: install jenkins
  ansible.builtin.dnf:
    name: jenkins
    state: present

- name: start jenkins
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
