- name: Download repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: install vault
  ansible.builtin.package:
    name: vault
    state: present