- name: set up prompt
  ansible.builtin.shell:
    set-prompt {{tool_name}}

- name: Download repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: install vault
  ansible.builtin.package:
    name: vault
    state: present

- name: copy vault config
  ansible.builtin.template:
    scr: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: start vault
  ansible.builtin.systemd_service:
    state: started
    enabled: yes
    name: vault